# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-auth

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  profile: personal
  region: ap-southeast-1

# The `functions` block defines what code to deploy
functions:
  authorize:
    handler: functions/authorize.handler
  getCats:
    handler: functions/getCats.handler
    events:
      - http:
          path: cats
          method: get
          cors: true
  getPangolins:
    handler: functions/getPangolins.handler
    events:
      - http:
          path: pangolins
          method: get
          cors: true
          authorizer: authorize
